// flow-typed signature: a23340c2b1554d9c832ccdfa6de0a1f4
// flow-typed version: <<STUB>>/casual-browserify_v^1.5.19-2/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'casual-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'casual-browserify' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'casual-browserify/scripts/generate' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/casual_browserify' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/casual' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/helpers' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ar_SY/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ar_SY/color' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ar_SY/date' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ar_SY/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ar_SY/text' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/color' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/date' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/de_DE/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/de_DE/date' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/de_DE/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/de_DE/text' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/en_CA/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/en_US/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/fr_FR/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/fr_FR/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/id_ID/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/internet' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/it_CH/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/it_CH/date' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/it_CH/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/it_IT/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/it_IT/date' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/it_IT/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/misc' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/nb_NO/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/nb_NO/color' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/nb_NO/date' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/nb_NO/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/nl_NL/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/nl_NL/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/number' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/payment' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/pt_BR/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/pt_BR/color' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/pt_BR/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ro_RO/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ro_RO/date' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ro_RO/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ru_RU/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ru_RU/color' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ru_RU/internet' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ru_RU/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/ru_RU/text' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/sv_SE/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/sv_SE/person' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/sv_SE/text' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/text' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/uk_UA/address' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/uk_UA/color' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/providers/uk_UA/text' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/require_provider_browserify' {
    declare module.exports: any;
}

declare module 'casual-browserify/src/safe_require_browserify' {
    declare module.exports: any;
}

declare module 'casual-browserify/test/casual' {
    declare module.exports: any;
}

declare module 'casual-browserify/utils/show' {
    declare module.exports: any;
}

// Filename aliases
declare module 'casual-browserify/scripts/generate.js' {
    declare module.exports: $Exports<'casual-browserify/scripts/generate'>;
}
declare module 'casual-browserify/src/casual_browserify.js' {
    declare module.exports: $Exports<'casual-browserify/src/casual_browserify'>;
}
declare module 'casual-browserify/src/casual.js' {
    declare module.exports: $Exports<'casual-browserify/src/casual'>;
}
declare module 'casual-browserify/src/helpers.js' {
    declare module.exports: $Exports<'casual-browserify/src/helpers'>;
}
declare module 'casual-browserify/src/providers/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/address'>;
}
declare module 'casual-browserify/src/providers/ar_SY/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ar_SY/address'>;
}
declare module 'casual-browserify/src/providers/ar_SY/color.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ar_SY/color'>;
}
declare module 'casual-browserify/src/providers/ar_SY/date.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ar_SY/date'>;
}
declare module 'casual-browserify/src/providers/ar_SY/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ar_SY/person'>;
}
declare module 'casual-browserify/src/providers/ar_SY/text.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ar_SY/text'>;
}
declare module 'casual-browserify/src/providers/color.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/color'>;
}
declare module 'casual-browserify/src/providers/date.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/date'>;
}
declare module 'casual-browserify/src/providers/de_DE/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/de_DE/address'>;
}
declare module 'casual-browserify/src/providers/de_DE/date.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/de_DE/date'>;
}
declare module 'casual-browserify/src/providers/de_DE/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/de_DE/person'>;
}
declare module 'casual-browserify/src/providers/de_DE/text.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/de_DE/text'>;
}
declare module 'casual-browserify/src/providers/en_CA/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/en_CA/address'>;
}
declare module 'casual-browserify/src/providers/en_US/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/en_US/address'>;
}
declare module 'casual-browserify/src/providers/fr_FR/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/fr_FR/address'>;
}
declare module 'casual-browserify/src/providers/fr_FR/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/fr_FR/person'>;
}
declare module 'casual-browserify/src/providers/id_ID/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/id_ID/address'>;
}
declare module 'casual-browserify/src/providers/internet.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/internet'>;
}
declare module 'casual-browserify/src/providers/it_CH/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/it_CH/address'>;
}
declare module 'casual-browserify/src/providers/it_CH/date.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/it_CH/date'>;
}
declare module 'casual-browserify/src/providers/it_CH/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/it_CH/person'>;
}
declare module 'casual-browserify/src/providers/it_IT/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/it_IT/address'>;
}
declare module 'casual-browserify/src/providers/it_IT/date.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/it_IT/date'>;
}
declare module 'casual-browserify/src/providers/it_IT/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/it_IT/person'>;
}
declare module 'casual-browserify/src/providers/misc.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/misc'>;
}
declare module 'casual-browserify/src/providers/nb_NO/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/nb_NO/address'>;
}
declare module 'casual-browserify/src/providers/nb_NO/color.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/nb_NO/color'>;
}
declare module 'casual-browserify/src/providers/nb_NO/date.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/nb_NO/date'>;
}
declare module 'casual-browserify/src/providers/nb_NO/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/nb_NO/person'>;
}
declare module 'casual-browserify/src/providers/nl_NL/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/nl_NL/address'>;
}
declare module 'casual-browserify/src/providers/nl_NL/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/nl_NL/person'>;
}
declare module 'casual-browserify/src/providers/number.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/number'>;
}
declare module 'casual-browserify/src/providers/payment.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/payment'>;
}
declare module 'casual-browserify/src/providers/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/person'>;
}
declare module 'casual-browserify/src/providers/pt_BR/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/pt_BR/address'>;
}
declare module 'casual-browserify/src/providers/pt_BR/color.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/pt_BR/color'>;
}
declare module 'casual-browserify/src/providers/pt_BR/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/pt_BR/person'>;
}
declare module 'casual-browserify/src/providers/ro_RO/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ro_RO/address'>;
}
declare module 'casual-browserify/src/providers/ro_RO/date.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ro_RO/date'>;
}
declare module 'casual-browserify/src/providers/ro_RO/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ro_RO/person'>;
}
declare module 'casual-browserify/src/providers/ru_RU/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ru_RU/address'>;
}
declare module 'casual-browserify/src/providers/ru_RU/color.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ru_RU/color'>;
}
declare module 'casual-browserify/src/providers/ru_RU/internet.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ru_RU/internet'>;
}
declare module 'casual-browserify/src/providers/ru_RU/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ru_RU/person'>;
}
declare module 'casual-browserify/src/providers/ru_RU/text.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/ru_RU/text'>;
}
declare module 'casual-browserify/src/providers/sv_SE/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/sv_SE/address'>;
}
declare module 'casual-browserify/src/providers/sv_SE/person.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/sv_SE/person'>;
}
declare module 'casual-browserify/src/providers/sv_SE/text.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/sv_SE/text'>;
}
declare module 'casual-browserify/src/providers/text.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/text'>;
}
declare module 'casual-browserify/src/providers/uk_UA/address.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/uk_UA/address'>;
}
declare module 'casual-browserify/src/providers/uk_UA/color.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/uk_UA/color'>;
}
declare module 'casual-browserify/src/providers/uk_UA/text.js' {
    declare module.exports: $Exports<'casual-browserify/src/providers/uk_UA/text'>;
}
declare module 'casual-browserify/src/require_provider_browserify.js' {
    declare module.exports: $Exports<'casual-browserify/src/require_provider_browserify'>;
}
declare module 'casual-browserify/src/safe_require_browserify.js' {
    declare module.exports: $Exports<'casual-browserify/src/safe_require_browserify'>;
}
declare module 'casual-browserify/test/casual.js' {
    declare module.exports: $Exports<'casual-browserify/test/casual'>;
}
declare module 'casual-browserify/utils/show.js' {
    declare module.exports: $Exports<'casual-browserify/utils/show'>;
}
